# Generated by Django 5.0.1 on 2025-09-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('medical_registration_no', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('DM', 'DM'), ('DNB', 'DNB'), ('Other', 'Other')], max_length=50, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('current_hospital', models.CharField(blank=True, max_length=255)),
                ('location_city_state', models.CharField(blank=True, max_length=255)),
                ('preferred_consultation_mode', models.CharField(blank=True, choices=[('In-person', 'In-person'), ('Teleconsultation', 'Teleconsultation'), ('Both', 'Both')], max_length=50, null=True)),
                ('languages_spoken', models.CharField(blank=True, max_length=255)),
                ('areas_of_interest', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NGOApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('registered_address', models.TextField(blank=True)),
                ('website_social', models.CharField(blank=True, max_length=255)),
                ('contact_full_name', models.CharField(max_length=255)),
                ('contact_designation', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_mobile', models.CharField(max_length=20)),
                ('partnership_reason', models.TextField(blank=True)),
                ('pillars', models.JSONField(blank=True, null=True)),
                ('support', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_org', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('NGO', 'NGO'), ('Doctor', 'Doctor'), ('Student', 'Student'), ('Corporate / CSR', 'Corporate / CSR'), ('Other', 'Other')], max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address_city', models.CharField(blank=True, max_length=255)),
                ('ways_to_support', models.JSONField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('One-time', 'One-time'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Project-based', 'Project-based')], max_length=50, null=True)),
                ('approx_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('skills_resources', models.TextField(blank=True)),
                ('reason_for_prankiran', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
