# Generated by Django 5.0.1 on 2025-09-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(help_text='Preferably WhatsApp', max_length=15)),
                ('parent_guardian_name', models.CharField(max_length=150)),
                ('parent_guardian_contact', models.CharField(max_length=15)),
                ('residential_address', models.TextField()),
                ('is_rural', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='Hindi', max_length=50)),
                ('education_level', models.CharField(choices=[('10th Appearing', '10th Appearing'), ('10th Passed', '10th Passed'), ('12th Appearing', '12th Appearing'), ('12th Passed', '12th Passed'), ('Graduation in Progress', 'Graduation in Progress')], max_length=50)),
                ('school_college_name', models.CharField(max_length=200)),
                ('board_university', models.CharField(blank=True, max_length=200, null=True)),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Other', 'Other')], default='Science', max_length=50)),
                ('subjects_studied', models.TextField(help_text='List subjects like PCM, PCB, etc.')),
                ('academic_performance', models.CharField(help_text='Last % or grades', max_length=50)),
                ('career_goal', models.CharField(choices=[('MBBS', 'MBBS'), ('BDS', 'BDS'), ('Nursing', 'Nursing'), ('Paramedical', 'Paramedical'), ('Allied Health Sciences', 'Allied Health Sciences'), ('Not Decided', 'Not Decided')], max_length=50)),
                ('wants_neet_classes', models.BooleanField(default=False)),
                ('needs_books', models.BooleanField(default=False)),
                ('wants_journals', models.BooleanField(default=False)),
                ('wants_mentorship', models.BooleanField(default=False)),
                ('wants_volunteering', models.BooleanField(default=False)),
                ('other_preferences', models.TextField(blank=True, null=True)),
                ('why_consider_you', models.TextField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
