# Generated by Django 5.0.1 on 2025-09-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'StudentApplication', 'verbose_name_plural': 'StudentApplication'},
        ),
    ]
