version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5437:5432"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --reload
    ports:
      - "8008:8000"
    volumes:
      - ./backend:/app  # Mount code for hot-reload
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env.prod
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Use dev Dockerfile for hot-reload
    command: npm run dev  # Development mode for instant updates
    ports:
      - "3007:3000"
    volumes:
      - ./frontend:/app  # Mount code for instant updates
      - /app/node_modules  # Preserve node_modules
      - /app/.next  # Preserve build cache
    env_file:
      - .env.prod
    environment:
      - NEXT_PUBLIC_API_URL=https://prankiran.com/api
      - API_URL=http://backend:8000/api
      - WATCHPACK_POLLING=true  # Enable file watching in Docker
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8009:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: